# Generated by Django 5.2.7 on 2025-10-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Preferências')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='Preferencias',
            field=models.ManyToManyField(blank=True, related_name='users', to='cadastro.preferencias', verbose_name='Tópicos de Interesse'),
        ),
    ]
