<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-06 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
=======
# Generated by Django 4.2.23 on 2025-10-15 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> e5a77b1c60d2c6a4c94003ff2637d404a065311e


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Tag')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Tag de Conteúdo',
                'verbose_name_plural': 'Tags de Conteúdo',
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> e5a77b1c60d2c6a4c94003ff2637d404a065311e
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(related_name='noticias', to='athena.tag')),
            ],
        ),
=======
>>>>>>> e5a77b1c60d2c6a4c94003ff2637d404a065311e
    ]
