# Generated by Django 5.2.7 on 2025-10-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='athena.tag'),
        ),
    ]
