# Generated by Django 5.2.7 on 2025-11-06 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='User',
            new_name='user',
        ),
    ]
