# Generated by Django 5.2.7 on 2025-10-30 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0002_tag_perfil_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='User',
            new_name='user',
        ),
    ]
